### ISSUE TITLE
复现问题

### ISSUE THREAD

**Issue by yyht** [dvlab-research/Step-DPO#2]
<img width="906" alt="企业微信截图_1bc47e3d-b09a-4db1-9957-d7d776666fc2" src="https://github.com/dvlab-research/Step-DPO/assets/14133687/3ae24af7-27d4-4d71-8520-bdb03837537b">
<img width="478" alt="企业微信截图_16593566-6c5f-4199-88d0-04b7503b4107" src="https://github.com/dvlab-research/Step-DPO/assets/14133687/8f39b472-9106-456f-a0c4-7baeb4f17bde">

**Comment by yyht** [comment]
使用 官方的deepseek--base-sft 和eval_math.py

**Comment by yyht** [comment]
使用官方的sft模型和评测脚本，好像 gsm8k 跑不到 对应的 paper文章的结果

**Comment by X-Lai** [comment]
Which prompt do you use?

I guess you may set `prompt` to `qwen2-boxed`. If this is the case, please set it to `alpaca` before using any of our SFT models. `qwen2-boxed` is for evaluating the open-source instruct models or our Step-DPO tuned ones.

**Comment by yyht** [comment]
i used deekseek-math prompt template



---原始邮件---
发件人: "Xin ***@***.***&gt;
发送时间: 2024年6月29日(周六) 中午1:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dvlab-research/Step-DPO] 复现问题 (Issue #2)




 
Which prompt do you use?
 
I guess you may set prompt to qwen2-boxed. If this is the case, please set it to alpaca before using any of our SFT models. qwen2-boxed is for evaluating the open-source instruct models or our Step-DPO tuned ones.

**Comment by X-Lai** [comment]
That's the reason. Please set it to `alpaca`.

**Comment by yyht** [comment]
<img width="739" alt="企业微信截图_856afacb-45af-49c6-9090-324e235118b2" src="https://github.com/dvlab-research/Step-DPO/assets/14133687/a77f0da2-d138-41c9-9356-180cee7e59f0">
yes, use alpaca-template could acheive similar results.

**Comment by yyht** [comment]
但好像还是差点

**Comment by X-Lai** [comment]
你用的antlr4-python3-runtime的版本是4.11吗？

**Comment by kaishxu** [comment]
> Which prompt do you use?
> 
> I guess you may set `prompt` to `qwen2-boxed`. If this is the case, please set it to `alpaca` before using any of our SFT models. `qwen2-boxed` is for evaluating the open-source instruct models or our Step-DPO tuned ones.

为什么使用SFT模型要用alpaca模板，而Step-DPO tuned模型要用qwen2-boxed模板，同一种模型这两个不应该是一致的吗（假如用的都是Qwen系列）？
