### ISSUE TITLE
About details of Step localization and Rectification

### ISSUE THREAD

**Issue by ToheartZhang** [dvlab-research/Step-DPO#3]
Thanks for your great work! I got good performance with your easy-to-use code and data. I am curious about the details of error localization and rectification, which seem to be illustrated in the appendix. However, the appendix is excluded in the arxiv version. Could you please explain more details about them, such as prompts, sampling methods, etc? Thanks again for your great work.

**Comment by X-Lai** [comment]
Thanks for your interest in our work.
We will update our arXiv paper soon. Please stay tuned.
