### ISSUE TITLE
Data Generation Pipeline

### ISSUE THREAD

**Issue by yapdianang** [dvlab-research/Step-DPO#4]
Hi, will the data generation pipeline be released to check for reproducibility? Thanks!

**Comment by X-Lai** [comment]
We will release the scripts for data generation with GPT-4o soon. Please stay tuned.

**Comment by X-Lai** [comment]
Hi, we have released the scripts for constructing the Step-DPO data: https://github.com/dvlab-research/Step-DPO/tree/main?tab=readme-ov-file#data-construction-pipeline. 
Welcome to generating data on your own!
