### ISSUE TITLE
Request for Citation

### ISSUE THREAD

**Issue by hbin0701** [dvlab-research/Step-DPO#5]
Dear authors,

I recently came across your paper and noticed that it shares a similar idea to our methodology presented in "Self-Explore to Avoid the Pit: Improving the Reasoning Capabilities of Language Models with Fine-grained Rewards" ([link](https://arxiv.org/abs/2404.10346)). Would you please consider including a citation to our paper in your references?

Thank you in advance!

Sincerely, 
Hyeonbin.

**Comment by X-Lai** [comment]
We will make updates in our latest version.

**Comment by xiami2019** [comment]
> Dear authors,
> 
> I recently came across your paper and noticed that it shares a similar idea to our methodology presented in "Self-Explore to Avoid the Pit: Improving the Reasoning Capabilities of Language Models with Fine-grained Rewards" ([link](https://arxiv.org/abs/2404.10346)). Would you please consider including a citation to our paper in your references?
> 
> Thank you in advance!
> 
> Sincerely, Hyeonbin.

Hi, it's a nice work.
Will you plan to open source the code and data?

**Comment by xiami2019** [comment]
> Dear authors,
> 
> I recently came across your paper and noticed that it shares a similar idea to our methodology presented in "Self-Explore to Avoid the Pit: Improving the Reasoning Capabilities of Language Models with Fine-grained Rewards" ([link](https://arxiv.org/abs/2404.10346)). Would you please consider including a citation to our paper in your references?
> 
> Thank you in advance!
> 
> Sincerely, Hyeonbin.

@hbin0701 
Hi, it's really a nice work.
Will you open source the code and data?

**Comment by hbin0701** [comment]
Hi @xiami2019 . Thanks for the interest. You can check the code in `https://github.com/hbin0701/Self-Explore`.
