### ISSUE TITLE
Great work， what about the computation resources needed for each experiment

### ISSUE THREAD

**Issue by yanghu819** [dvlab-research/Step-DPO#6]

**Comment by X-Lai** [comment]
Hi, thanks for your interest in our work. 

We conduct all experiments on 8*A100 GPUs. It takes ~2 hours for 7B models and ~20 hours for ~70B models.

**Comment by heyubox** [comment]
Did you use Lora to finetune ~70B model on 8*A100 GPUs? I got OOM error when finetuning full parameters ~70B models.

**Comment by yanghu819** [comment]
I use 2 A100 with each batch=1 (qwen 7b), but still OOM, that makes me hard to debug and learn, do you have any advice?

**Comment by heyubox** [comment]
> I use 2 A100 with each batch=1 (qwen 7b), but still OOM, that makes me hard to debug and learn, do you have any advice?

Lora could be helpful for debugging. But I can't ensure you reproduce the result because I don't reproduce the results when fine-tuning the ~70B models.
