### ISSUE TITLE
Question about the DPO vs. Step-DPO.

### ISSUE THREAD

**Issue by flow3rdown** [dvlab-research/Step-DPO#7]
Hi, nice work!

I have a question about the comparison between DPO and Step-DPO in Section 4.3. Could you tell me the difference between DPO and StepDPO during training? Is the form of data different?

**Comment by X-Lai** [comment]
The key difference is that Step-DPO compares the reasoning steps, while DPO compares the holistic answers. This can be done by using a different data format, and the implementation of the training objective can be kept the same.

**Comment by flow3rdown** [comment]
Thanks!
