### ISSUE TITLE
questions about some parameter in config_full.yaml

### ISSUE THREAD

**Issue by kaishxu** [dvlab-research/Step-DPO#8]
<img width="812" alt="Screenshot 2024-07-15 at 20 33 30" src="https://github.com/user-attachments/assets/7412c575-27d7-41e8-b56f-09cb66237df3">

Hello!

I am confused about the parameters "model_name_or_path:" and "data_path:". These paths are missing in the repo. So, do they play a role in training?

**Comment by X-Lai** [comment]
Sorry about that. I forgot to clean these paths before releasing the code. Now I have fixed it. 

Then, you should reset them to your desired paths in the training command.
